# Generated by Django 4.1 on 2022-08-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lei', '0002_alter_docente_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='nome',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='news',
            name='cabecalho',
            field=models.CharField(max_length=250),
        ),
    ]
