# Generated by Django 4.1 on 2022-08-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lei', '0004_alter_anoletivo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='imagelink',
            field=models.URLField(blank=True),
        ),
    ]
