# Generated by Django 4.1 on 2022-08-28 17:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lei', '0005_alter_news_imagelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dataDeNascimento', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('numeroDeTelefone', models.PositiveIntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lei.turma')),
            ],
        ),
    ]
