# Generated by Django 4.1 on 2022-08-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lei', '0006_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='numeroDeTelefone',
            field=models.PositiveIntegerField(blank=True, default='+239'),
        ),
    ]
