# Generated by Django 4.1 on 2022-08-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lei', '0007_docente_numerodetelefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/news'),
        ),
        migrations.AddField(
            model_name='nota',
            name='ficheiro',
            field=models.FileField(blank=True, null=True, upload_to='nota/'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='ficheiro',
            field=models.FileField(blank=True, null=True, upload_to='recurso/'),
        ),
    ]
