# Generated by Django 4.1 on 2022-08-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lei', '0008_news_imagem_nota_ficheiro_recurso_ficheiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='ficheiro',
            field=models.FileField(null=True, upload_to='nota/'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='ficheiro',
            field=models.FileField(null=True, upload_to='recurso/'),
        ),
    ]
