# Generated by Django 4.1 on 2022-08-31 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lei', '0009_alter_nota_ficheiro_alter_recurso_ficheiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
