# Generated by Django 4.1 on 2022-09-04 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lei', '0011_calendario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendario',
            old_name='data',
            new_name='dataFim',
        ),
        migrations.AddField(
            model_name='calendario',
            name='dataInicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
