# Generated by Django 4.1 on 2022-09-09 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lei', '0012_rename_data_calendario_datafim_calendario_datainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lei.docente'),
        ),
    ]
