# Generated by Django 4.1 on 2022-09-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lei', '0013_alter_recurso_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='numeroDeTelefone',
            field=models.PositiveIntegerField(blank=True, default='00239', null=True),
        ),
    ]
