# Generated by Django 4.1 on 2022-09-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lei', '0014_alter_aluno_numerodetelefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
