# Generated by Django 4.1 on 2022-09-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lei', '0015_alter_aluno_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendario',
            old_name='dataFim',
            new_name='data_Fim',
        ),
        migrations.RenameField(
            model_name='calendario',
            old_name='dataInicio',
            new_name='data_Inicio',
        ),
    ]
