# Generated by Django 4.1 on 2022-09-15 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lei', '0017_rename_data_fim_calendario_datafim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='dataDeNascimento',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='data de nascimento'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='numeroDeTelefone',
            field=models.PositiveIntegerField(blank=True, default='00239', null=True, verbose_name='numero de telefone'),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='dataFim',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de fim'),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='dataInicio',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de inicio'),
        ),
    ]
