# Generated by Django 4.1 on 2022-09-19 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lei', '0018_alter_aluno_datadenascimento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendario',
            old_name='detallhe',
            new_name='detalhe',
        ),
    ]
